language: node_js
node_js:
  - "0.10"
env:
  - NODE_ENV=test
services:
  - mongodb
before_script:
  - npm install -g gulp
  - cd app && npm install
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script: gulp test