language: node_js
node_js:
- '0.10'
env:
- NODE_ENV=test
services:
- mongodb
before_script:
- npm install -g gulp
- cd app && npm install
- cd ../api && npm install
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
script: cd ../app && gulp test && cd ../api && npm test
after_script:
- npm install -g istanbul
- npm install -g codeclimate-test-reporter
- instanbul cover node_modules/.bin/_mocha
- CODECLIMATE_REPO_TOKEN=26b909313e75f87119fa0af40ae5dbddf1fb8aefb7f3daea31401981d85d0b3a codeclimate < coverage/lcov.info
deploy:
- provider: s3
  skip_cleanup: true
  access_key_id:
    secure: Alsxg+sG80S2ku3kO5Shc669QC+NISTh6/PBOg09QNYLqxiZwhVs62TC201eoTpf8DxYPs1qBgPq+FiRo/TELTHWkpafwSra26oWh+y1fc7j+zps+RK+fK9+3x9jJMrc2aYAM2rRK+beXBfzg+vB9obW7UqXCpMznBWeTa2shNI=
  secret_access_key:
    secure: q8WvDu6NzJzIxSVhbhayTnlt0DilSUJgOYxZ6wcD7+4o3/xnHe+dq1CC1/rxiBl+oeufz7XxdpVq3UuNHi9Ive1Vyvb1kwUIZj3ncHt6A1jAY0OTV1HTT763DlLv47mMOXexP/ly/Ik+GPbwV5VR/8U0z+uonEZpQAWGyPJ8GyQ=
  bucket: majora.upplication.com
  region: eu-west-1
  local_dir: ../app/dist
  on:
    tags: true
    all_branches: true
- provider: elasticbeanstalk
  skip_cleanup: true
  access_key_id:
    secure: Alsxg+sG80S2ku3kO5Shc669QC+NISTh6/PBOg09QNYLqxiZwhVs62TC201eoTpf8DxYPs1qBgPq+FiRo/TELTHWkpafwSra26oWh+y1fc7j+zps+RK+fK9+3x9jJMrc2aYAM2rRK+beXBfzg+vB9obW7UqXCpMznBWeTa2shNI=
  secret_access_key:
    secure: q8WvDu6NzJzIxSVhbhayTnlt0DilSUJgOYxZ6wcD7+4o3/xnHe+dq1CC1/rxiBl+oeufz7XxdpVq3UuNHi9Ive1Vyvb1kwUIZj3ncHt6A1jAY0OTV1HTT763DlLv47mMOXexP/ly/Ik+GPbwV5VR/8U0z+uonEZpQAWGyPJ8GyQ=
  app: majora-api
  env: majora-api
  region: eu-west-1
  bucket-name: majora-api
  local_dir: ../api
  on:
    tags: true
    all_branches: true